---
title: "Extra Credit"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data Load ## 

```{r}
boston = read.csv("/Users/dipakkrishnan/Downloads/listings-3.csv")
colnames(review)
boston.reduced = subset(boston, select = c("id","host_response_time", "host_response_rate", "host_is_superhost", "host_identity_verified", "host_listings_count", "neighbourhood_group_cleansed", "property_type", "room_type", "latitude", "longitude", "guests_included", "accommodates",  "bathrooms", "bedrooms", "beds",  "amenities",  "price" , "cleaning_fee", "minimum_nights", "maximum_nights", "instant_bookable", "cancellation_policy", "review_scores_rating"))
```




## Data Preprocessing ## 

```{r}
boston.reduced$host_is_superhost = as.factor(as.numeric(boston.reduced$host_is_superhost) -1)
boston.reduced$host_identity_verified = as.factor(as.numeric(boston.reduced$host_identity_verified) -1)
boston.reduced$instant_bookable = as.factor(as.numeric(boston.reduced$instant_bookable) -1)
boston.reduced$host_response_rate = as.numeric(sub("%", "", boston.reduced$host_response_rate)) / 100
boston.reduced$host_response_time = as.factor(unclass(boston.reduced$host_response_time) -1)
boston.reduced$cleaning_fee = as.numeric(sub("$", "", boston.reduced$cleaning_fee, fixed = T))
boston.reduced$price = as.numeric(gsub("$", "", boston.reduced$price, fixed = T))
boston.reduced$cancellation_policy = as.factor(as.numeric(boston.reduced$cancellation_policy))
boston.reduced$review_scores_rating = as.numeric(boston.reduced$review_scores_rating)

boston.reduced$cleaning_fee[is.na(boston.reduced$cleaning_fee)] = 0
boston.reduced$price[is.na(boston.reduced$price)] = 0
boston.reduced$host_listings_count[is.na(boston.reduced$host_listings_count)] = 0 
boston.reduced$bathrooms[is.na(boston.reduced$bathrooms)] = 0
boston.reduced$bedrooms[is.na(boston.reduced$bedrooms)] = 0
boston.reduced$beds[is.na(boston.reduced$beds)] = 0
boston.reduced$neighbourhood_group_cleansed = NULL
boston.reduced$host_response_rate = NULL
```


```{r}
greater = which(boston.reduced$review_scores_rating >= 95) # as 1
less = which(boston.reduced$review_scores_rating <= 90) # as 0
indices = c(greater,less)
boston.reduced = boston.reduced[indices,]
boston.reduced$review_scores_rating = ifelse(boston.reduced$review_scores_rating <= 90,0,1)

sum(is.na(boston.reduced))
head(boston.reduced)
```

## Amenities ## 


```{r}
# library: stringr
library(stringr)
amenities = sapply(boston.reduced$amenities, FUN=function(x) {
  # some function that just splits up all the words in each row of amenities
  s = toString(x)
  s = strsplit(s[[1]],",")
  newS = str_replace(s[[1]],'\\{',"")
  newS = str_replace(newS,'\\}',"")
  newS = str_replace(newS,'\"',"")
  newS = str_replace(newS,'\"',"")
  tolower(newS)
})


num.amenities = c()
for(i in 1:length(boston.reduced$amenities)) {
  num.amenities[i] = length(amenities[[i]])
}
boston.reduced$amenities = NULL
boston.reduced$property_type = NULL
boston.reduced$num_amenities = num.amenities
boston.reduced$review_scores_rating = as.factor(boston.reduced$review_scores_rating)
```


## Distance Measure ## 

```{r}
library(geosphere)
fenway.lat = 42.3467 ; fenway.long = -71.0972
fanueil.lat = 42.3603 ; fanueil.long = -71.0547
freedom.lat = 42.3560 ; freedom.long = -71.0545

fenway.dist = c()
fanueil.dist = c()
freedom.dist = c()
for(i in 1:length(boston.reduced$latitude)) {
  fenway.dist[i] = distm(c(fenway.long, fenway.lat), c(boston.reduced$longitude[i], boston.reduced$latitude[i]), fun = distGeo) / 1609.344
  fanueil.dist[i] = distm(c(fanueil.long, fanueil.lat), c(boston.reduced$longitude[i], boston.reduced$latitude[i]), fun = distGeo) / 1609.344
  freedom.dist[i] = distm(c(freedom.long, freedom.lat), c(boston.reduced$longitude[i], boston.reduced$latitude[i]), fun = distGeo) / 1609.344
}
boston.reduced$fenway_dist = fenway.dist ; boston.reduced$fanueil_dist = fanueil.dist ; boston.reduced$freedom_dist = freedom.dist 
boston.reduced = boston.reduced[-1785,]
```

## Train Test split ## 

```{r}
nR <- nrow(boston.reduced)
boston.review <- boston.reduced[sample(nR), ]
train.indicesR <- 1:round(0.7 * nR)
trainR <- boston.review[train.indicesR,]
test.indicesR <- (round(0.7 * nR) + 1):nR
testR <- boston.review[test.indicesR,]
```


## MLR ## 

```{r}
mlr.bos = lm(price~., data=trainR)
summary(mlr.bos)
samp.price.bos = sample(rep(1:nfold, ceiling(nrow(boston.reduced)/nfold))[1:nrow(boston.reduced)])
mse = c()
for(k in 1:nfold) {
  testd <- boston.reduced[which(samp.price.bos==k), ]
  traind <- boston.reduced[-which(samp.price.bos==k), ]
  lm.reg = lm(price~., data = traind)
  lm.reg.pred = predict(lm.reg, newdata = testd)
  mse[k] = mean((lm.reg.pred - testd$price)^2)
}
mse = mean(mse)
```

## Trees ## 


```{r}
library(rpart)
tree.ec = rpart(price~., data = trainR)
plotcp(tree.ec)
pruned.ec = prune(tree.ec, cp = 0.024)

mse.tree.ec= c()
mse.prune.ec = c()

for(k in 1:nfold) {
  testd <- boston.reduced[which(samp.price.bos==k), ]
  traind <- boston.reduced[-which(samp.price.bos==k), ]
  
  tree = rpart(price~., data = traind)
  pruned.tree = prune(tree, cp = 0.024)
    
  tree.predictions = predict(tree, testd)
  pruned.tree.predictions = predict(pruned.tree, testd)
  
  mse.tree.ec[k] = mean((tree.predictions - testd$price)^2)
  mse.prune.ec[k] = mean((pruned.tree.predictions - testd$price)^2)
}
mse.tree.ec = mean(mse.tree.ec)
mse.prune.ec = mean(mse.prune.ec)

```

## Random Forest ## 

```{r}
library(randomForest)
rf.ec = randomForest(price~., data = trainR, ntree = 500)
varImpPlot(rf.ec, sort = T, n.var = 15, main = "Top 15 Variables Training By Importance")

mse.tree.rf = c()

for(k in 1:nfold) {
  testd <- boston.reduced[which(samp.price.bos==k), ]
  traind <- boston.reduced[-which(samp.price.bos==k), ]
  
  rf = randomForest(price~., data = trainR, ntree = 500)

  rf.predictions = predict(rf, newdata = testd)
  
  mse.tree.rf[k] = mean((rf.predictions - testd$price)^2)
}

mse.tree.rf = mean(mse.tree.rf)
predictions.rf = predict(rf.ec, newdata = testR)
```


## Naive Bayes ## 

```{r}
library(e1071)
naive = naiveBayes(review_scores_rating~., data = trainR)

misclass.naive = c()

for(k in 1:nfold) {
  testd <- boston.reduced[which(samp.price.bos==k), ]
  traind <- boston.reduced[-which(samp.price.bos==k), ]
  
  naive = naiveBayes(review_scores_rating~., data = traind)

  naive.predictions = predict(naive, newdata = testd)
  
  misclass.naive[k] = mean(naive.predictions != as.factor(testd$review_scores_rating))
}

misclass.naive = mean(misclass.naive)
```

## Log Reg ## 

```{r}
log.reg = glm(review_scores_rating~., data = trainR, family="binomial")

misclass.log = c()

for(k in 1:nfold) {
  testd <- boston.reduced[which(samp.price.bos==k), ]
  traind <- boston.reduced[-which(samp.price.bos==k), ]
    
  log.mod = glm(review_scores_rating~., data = traind, family="binomial")

  log.predictions = predict(log.mod, newdata = testd)
  
  misclass.log[k] = mean(log.predictions != as.factor(testd$review_scores_rating))
}
misclass.log = mean(misclass.log)
```


## SVM Linear ## 

```{r}
library(e1071)

svm.misclass = c()
for(k in 1:nfold) {
  testd <- boston.reduced[which(samp.price.bos==k), ]
  traind <- boston.reduced[-which(samp.price.bos==k), ]
  
  svm = svm(review_scores_rating~., data = traind, kernel = "linear")

  svm.predictions = predict(svm, newdata = testd)
  
  svm.misclass[k] = mean(svm.predictions != as.factor(testd$review_scores_rating))
}

svm.misclass = mean(svm.misclass)
```

## SVM Poly ## 

```{r}
library(e1071)

svm.misclass.poly = c()
for(k in 1:nfold) {
  testd <- boston.reduced[which(samp.price.bos==k), ]
  traind <- boston.reduced[-which(samp.price.bos==k), ]
  
  svm = svm(review_scores_rating~., data = traind, kernel = "polynomial")

  svm.predictions = predict(svm, newdata = testd)
  
  svm.misclass.poly[k] = mean(svm.predictions != as.factor(testd$review_scores_rating))
}

svm.misclass.poly = mean(svm.misclass.poly)
```



## SVM Radial ##

```{r}
library(e1071)

svm.misclass.radial = c()
for(k in 1:nfold) {
  testd <- boston.reduced[which(samp.price.bos==k), ]
  traind <- boston.reduced[-which(samp.price.bos==k), ]
  
  svm = svm(review_scores_rating~., data = traind, kernel = "radial")

  svm.predictions = predict(svm, newdata = testd)
  
  svm.misclass.radial[k] = mean(svm.predictions != as.factor(testd$review_scores_rating))
}

svm.misclass.radial = mean(svm.misclass.radial)
```

## Boosting ## 

```{r}


boost.misclass = c()
for(k in 1:nfold) {
  testd <- boston.reduced[which(samp.price.bos==k), ]
  traind <- boston.reduced[-which(samp.price.bos==k), ]
  
  boost = boosting(review_scores_rating~., data = traind, mfinal = 100, coeflearn = "Freund")

  boost.pred = predict.boosting(boost, newdata = testd)
  
  boost.misclass[k] = boost.pred$error
}
boost.misclass = mean(boost.misclass)


```


## Random Forest ## 

```{r}

rf.misclass = c()

for(k in 1:nfold) {
  testd <- boston.reduced[which(samp.price.bos==k), ]
  traind <- boston.reduced[-which(samp.price.bos==k), ]
  
  rf = randomForest(review_scores_rating~., data = traind, ntrees = 500)

  rf.pred = predict(rf, newdata = testd)
  
  rf.misclass[k] = mean(rf.pred != as.factor(testd$review_scores_rating))
}
rf.misclass = mean(rf.misclass)

rf.mod = randomForest(review_scores_rating~., data = trainR, ntrees = 500)
varImpPlot(rf.mod, sort = T, n.var = 15, main = "Top 15 Variables Training By Importance")
```






